"""Add card_no to FuelRequest

Revision ID: 0dba2c882182
Revises: bfc387b60e7a
Create Date: 2025-07-17 17:51:36.473563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dba2c882182'
down_revision = 'bfc387b60e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_no', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.drop_column('card_no')

    # ### end Alembic commands ###
