"""Extended Vehicle model with model and color

Revision ID: 67a7c4c672f5
Revises: 74d9d5433af1
Create Date: 2025-07-09 13:27:35.976013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67a7c4c672f5'
down_revision = '74d9d5433af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_no', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['card_no'])
        batch_op.drop_constraint(batch_op.f('vehicles_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('vehicles_ibfk_1'), 'departments', ['department_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('department')
        batch_op.drop_column('color')
        batch_op.drop_column('model')
        batch_op.drop_column('card_no')

    # ### end Alembic commands ###
