"""Add updated_at to fuel_requests

Revision ID: 73f99c49b8cb
Revises: b635ae4688f4
Create Date: 2025-07-25 12:57:16.802909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f99c49b8cb'
down_revision = 'b635ae4688f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
