"""Remove fuel_station field

Revision ID: 74d9d5433af1
Revises: 8da115a7778e
Create Date: 2025-07-08 14:49:58.408551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74d9d5433af1'
down_revision = '8da115a7778e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.drop_column('fuel_station')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_station', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
