"""Add amount_loaded to fuel_requests

Revision ID: b635ae4688f4
Revises: 0dba2c882182
Create Date: 2025-07-25 01:12:32.421492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b635ae4688f4'
down_revision = '0dba2c882182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_loaded', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.drop_column('amount_loaded')

    # ### end Alembic commands ###
