"""Add amount_last_loaded to fuel_requests

Revision ID: bfc387b60e7a
Revises: e7bff478b0e8
Create Date: 2025-07-15 13:50:39.098121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfc387b60e7a'
down_revision = 'e7bff478b0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_card_records', schema=None) as batch_op:
        batch_op.alter_column('card_no',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_last_loaded', sa.Float(), nullable=True))
        batch_op.drop_column('amount_lastloaded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_lastloaded', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('amount_last_loaded')

    with op.batch_alter_table('fuel_card_records', schema=None) as batch_op:
        batch_op.alter_column('card_no',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
