"""Rename plate_number to registration_no in Vehicle

Revision ID: c268e5c005d6
Revises: 67a7c4c672f5
Create Date: 2025-07-09 13:44:05.790262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c268e5c005d6'
down_revision = '67a7c4c672f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_no', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_vehicles_plate_number'), type_='unique')
        batch_op.create_unique_constraint('uq_vehicles_plate_number', ['registration_no'])
        batch_op.drop_column('plate_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('uq_vehicles_plate_number', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_vehicles_plate_number'), ['plate_number'])
        batch_op.drop_column('registration_no')

    # ### end Alembic commands ###
