"""Add card_no to FuelCardRecord

Revision ID: e7bff478b0e8
Revises: c268e5c005d6
Create Date: 2025-07-15 12:29:17.494117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7bff478b0e8'
down_revision = 'c268e5c005d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_card_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_no', sa.String(length=50), nullable=True))
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_card_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('card_no')

    # ### end Alembic commands ###
